[phases.setup]
nixPkgs = ["...", "postgresql", "nodejs-18_x"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["echo 'Build phase completed'"]

[start]
cmd = "chmod +x init.sh && ./init.sh && npm start"